# Generated by Django 3.2.5 on 2023-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL conﬁg.', max_length=31, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=31)),
                ('slug', models.SlugField(help_text='A label for URL conﬁg.', max_length=31, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.CharField(db_index=True, max_length=31)),
                ('entry_date', models.DateField(verbose_name='date of entry')),
                ('tags', models.ManyToManyField(blank=True, to='goods.Tag')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'entry_date',
            },
        ),
    ]
