# Generated by Django 3.2.5 on 2023-11-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Item',
            name='estimated_price',
            field=models.IntegerField(default=0),
            )
    ]
