# Generated by Django 3.2.5 on 2023-11-13 10:22

from django.db import migrations, models


def add_total_item_estimated_price_data(apps, schema_editor):
    Item = apps.get_model(
        'goods', 'Item')

    query = Item.objects.all()
    for item in query:
        item.save()


def remove_total_item_estimated_price_data(apps, schema_editor):
    Item = apps.get_model(
        'goods', 'Item')

    Item.objects.update(total_item_estimated_price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_item_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='Item',
            name='total_item_estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
            ),
        migrations.RunPython(
            add_total_item_estimated_price_data,
            reverse_code=remove_total_item_estimated_price_data
            ),
    ]
