# Generated by Django 3.2.5 on 2023-11-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
