# Generated by Django 3.2.5 on 2023-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_delete_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_inventory_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
