# Generated by Django 3.2.5 on 2023-11-23 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    def add_currency_data(apps, schema_editor):
        Item = apps.get_model(
            'goods', 'Item')

#        currency = list(settings.OSCAR_CURRENCIES).copy()
        query = Item.objects.all()
        for item in query:
#            item.update(currency=list(settings.OSCAR_CURRENCIES).copy())
            item.save()

    def remove_currency_data(apps, schema_editor):
        Item = apps.get_model(
            'goods', 'Item')

        Item.objects.update(currency='')

    dependencies = [
        ('goods', '0011_item_total_inventory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='Item',
            name='currency',
            field=models.CharField(max_length=255, blank=True),
            ),
        migrations.RunPython(
            add_currency_data,
            reverse_code=remove_currency_data
            ),
    ]
