# Generated by Django 3.2.5 on 2023-11-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_inventory_value',
        ),
    ]
