# Generated by Django 3.2.5 on 2023-11-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_remove_item_total_inventory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
