# Generated by Django 3.2.5 on 2023-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_remove_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
