# Generated by Django 3.2.5 on 2023-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, default=['EUR', 'CAD', 'USD'], max_length=255),
        ),
    ]
