# Generated by Django 3.2.5 on 2023-11-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_alter_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
