# Generated by Django 3.2.5 on 2023-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_remove_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[(0, 'EUR'), (2, 'USD'), (1, 'CAD')], max_length=255),
        ),
    ]
